import type { CostBand, EnglishBand, University } from './universities';

type Seed = [string, string, string, string];
const all = ['IT', 'Бизнес', 'Медицина', 'Дизайн', 'Инженерия', 'Право'];
const defaults: Record<string, [string, EnglishBand, CostBand]> = {
  'США': ['Английский', 'C1', 'Высокая'], 'Канада': ['Английский / французский', 'C1', 'Высокая'],
  'Германия': ['Немецкий / английский', 'C1', 'Низкая'], 'Великобритания': ['Английский', 'C1', 'Высокая'],
  'Франция': ['Французский / английский', 'B2', 'Низкая'], 'Нидерланды': ['Английский / нидерландский', 'C1', 'Высокая'],
  'Южная Корея': ['Корейский / английский', 'C1', 'Средняя'], 'Япония': ['Японский / английский', 'C1', 'Средняя'],
  'Китай': ['Китайский / английский', 'B2', 'Средняя'],
};
const seeds: Seed[] = [
  ['Stanford University', 'Стэнфорд', 'США', 'https://admission.stanford.edu/'], ['Massachusetts Institute of Technology', 'Кембридж', 'США', 'https://mitadmissions.org/'], ['Harvard University', 'Кембридж', 'США', 'https://college.harvard.edu/admissions'], ['University of California, Berkeley', 'Беркли', 'США', 'https://admissions.berkeley.edu/'], ['Georgia Institute of Technology', 'Атланта', 'США', 'https://admission.gatech.edu/'],
  ['McMaster University', 'Гамильтон', 'Канада', 'https://future.mcmaster.ca/'], ["Queen's University", 'Кингстон', 'Канада', 'https://www.queensu.ca/admission/'], ['Western University', 'Лондон', 'Канада', 'https://welcome.uwo.ca/'], ['Université de Montréal', 'Монреаль', 'Канада', 'https://admission.umontreal.ca/'], ['Dalhousie University', 'Галифакс', 'Канада', 'https://www.dal.ca/admissions.html'],
  ['University of Freiburg', 'Фрайбург', 'Германия', 'https://uni-freiburg.de/en/studies/'], ['University of Bonn', 'Бонн', 'Германия', 'https://www.uni-bonn.de/en/studying'], ['University of Göttingen', 'Гёттинген', 'Германия', 'https://www.uni-goettingen.de/en/studying/3811.html'], ['TU Dresden', 'Дрезден', 'Германия', 'https://tu-dresden.de/studium/vor-dem-studium/bewerbung'], ['University of Stuttgart', 'Штутгарт', 'Германия', 'https://www.uni-stuttgart.de/en/study/application/'],
  ['University of Cambridge', 'Кембридж', 'Великобритания', 'https://www.undergraduate.study.cam.ac.uk/'], ['Imperial College London', 'Лондон', 'Великобритания', 'https://www.imperial.ac.uk/study/apply/undergraduate/'], ['London School of Economics', 'Лондон', 'Великобритания', 'https://www.lse.ac.uk/study-at-lse/Undergraduate'], ["King's College London", 'Лондон', 'Великобритания', 'https://www.kcl.ac.uk/study/undergraduate'], ['University of Birmingham', 'Бирмингем', 'Великобритания', 'https://www.birmingham.ac.uk/study/undergraduate'],
  ['Université PSL', 'Париж', 'Франция', 'https://psl.eu/en/education/admissions'], ['École Normale Supérieure de Lyon', 'Лион', 'Франция', 'https://www.ens-lyon.fr/en/studies/admissions'], ['CentraleSupélec', 'Жиф-сюр-Иветт', 'Франция', 'https://www.centralesupelec.fr/en/admissions'], ['Toulouse Capitole University', 'Тулуза', 'Франция', 'https://www.ut-capitole.fr/home/international'], ['University of Montpellier', 'Монпелье', 'Франция', 'https://www.umontpellier.fr/en/international'],
  ['Erasmus University Rotterdam', 'Роттердам', 'Нидерланды', 'https://www.eur.nl/en/education/bachelor-programmes/admission'], ['Radboud University', 'Неймеген', 'Нидерланды', 'https://www.ru.nl/en/education/application-and-admission'], ['Vrije Universiteit Amsterdam', 'Амстердам', 'Нидерланды', 'https://vu.nl/en/education/more-about/applying-for-a-bachelors-programme'], ['Wageningen University & Research', 'Вагенинген', 'Нидерланды', 'https://www.wur.nl/en/education-programmes/bachelor/practical-information/admission.htm'], ['Tilburg University', 'Тилбург', 'Нидерланды', 'https://www.tilburguniversity.edu/education/bachelors-programs/application'],
  ['UNIST', 'Ульсан', 'Южная Корея', 'https://admu-intl.unist.ac.kr/'], ['Gwangju Institute of Science and Technology', 'Кванджу', 'Южная Корея', 'https://www.gist.ac.kr/iadm/'], ['Ewha Womans University', 'Сеул', 'Южная Корея', 'https://admission.ewha.ac.kr/admission/html/international/guide.asp'], ['Sogang University', 'Сеул', 'Южная Корея', 'https://admission.sogang.ac.kr/'], ['Pusan National University', 'Пусан', 'Южная Корея', 'https://international.pusan.ac.kr/'],
  ['Hokkaido University', 'Саппоро', 'Япония', 'https://www.global.hokudai.ac.jp/admissions/'], ['Kyushu University', 'Фукуока', 'Япония', 'https://www.kyushu-u.ac.jp/en/admission/'], ['University of Tsukuba', 'Цукуба', 'Япония', 'https://www.tsukuba.ac.jp/en/admissions/'], ['Sophia University', 'Токио', 'Япония', 'https://adm.sophia.ac.jp/eng/'], ['Kobe University', 'Кобе', 'Япония', 'https://www.kobe-u.ac.jp/en/academics/admissions/'],
  ['Sun Yat-sen University', 'Гуанчжоу', 'Китай', 'https://iso.sysu.edu.cn/'], ['Harbin Institute of Technology', 'Харбин', 'Китай', 'https://studyathit.hit.edu.cn/'], ["Xi'an Jiaotong University", 'Сиань', 'Китай', 'https://sie.xjtu.edu.cn/en/'], ['Tongji University', 'Шанхай', 'Китай', 'https://study.tongji.edu.cn/'], ['Beihang University', 'Пекин', 'Китай', 'https://is.buaa.edu.cn/en/'],
];
export const catalogStrongExpansion: University[] = seeds.map(([name, city, country, url]) => {
  const [language, englishBand, cost] = defaults[country];
  return { name, city, country, url, language, englishBand, cost, directions: all, funding: true, housing: true };
});
