import { useEffect, useState } from 'react';

type Opportunity = {
  name: string; age: string; summary: string; tag: string; intro: string;
  benefits: string[]; steps: string[]; important: string; url: string; portfolio?: string;
};

const opportunities: Opportunity[] = [
  { name: 'FLEX', age: 'Обычно для школьников 8–10 классов', tag: 'Обмен', summary: 'Учебный год в американской школе.', intro: 'FLEX — бесплатная конкурсная программа обмена. Победитель один учебный год живёт в принимающей семье и учится в школе США, а затем возвращается домой.', benefits: ['Практика английского каждый день', 'Опыт жизни и учёбы в другой стране', 'Новые друзья и самостоятельность', 'Перелёт, проживание и основные расходы покрывает программа'], steps: ['Проверить возраст и класс для текущего набора', 'Заполнить заявку и пройти тесты', 'Пройти интервью и написать эссе', 'Подготовить документы, если прошёл отбор'], important: 'Конкурс высокий. Участие бесплатное, но точный возраст и сроки меняются каждый год.', url: 'https://kazakhstan.americancouncils.org/flex-en' },
  { name: 'EducationUSA', age: 'Для школьников и поступающих', tag: 'Поддержка', summary: 'Официальная помощь с поступлением в США.', intro: 'EducationUSA — сеть консультационных центров Госдепартамента США. Здесь объясняют, как найти вуз, подготовить заявку, поискать финансирование и оформить студенческую визу.', benefits: ['Понятная информация о вузах США', 'План из пяти шагов поступления', 'Вебинары и консультации', 'Помощь в поиске финансовой поддержки'], steps: ['Найти ближайший центр', 'Изучить пять шагов поступления', 'Составить список университетов', 'Записаться на консультацию или вебинар'], important: 'Это не грант и не университет. Центр помогает разобраться, но решение о поступлении принимает вуз.', url: 'https://educationusa.state.gov/' },
  { name: 'DAAD', age: 'Чаще для студентов и выпускников', tag: 'Стипендии', summary: 'Программы и финансирование для Германии.', intro: 'DAAD — Германская служба академических обменов. На её сайте можно искать учебные программы и стипендии для обучения или исследований в Германии.', benefits: ['Большая база стипендий', 'Поиск программ в Германии', 'Информация о языке и документах', 'Возможности для учёбы и исследований'], steps: ['Определить свой уровень обучения', 'Найти подходящую программу в базе', 'Проверить требования именно этой стипендии', 'Подготовить язык и документы заранее'], important: 'Большинство стипендий DAAD рассчитано на выпускников вузов, магистрантов и исследователей. Школьнику полезно использовать базу для планирования будущего.', url: 'https://www.daad.de/en/studying-in-germany/scholarships/' },
  { name: 'ЮНИСЕФ Жастары', age: 'Для молодёжи 16–35 лет', tag: 'Волонтёрство', summary: 'Социальные проекты, обучение и волонтёрские задания по всему Казахстану.', intro: 'Волонтёрская программа ЮНИСЕФ помогает участвовать в социальных, образовательных и экологических инициативах. Можно развивать лидерство, организационные навыки и делать полезные проекты для своего сообщества.', benefits: ['Опыт участия в реальных социальных проектах', 'Обучение и сертификаты', 'Навыки организации, общения и командной работы', 'Понятный вклад, который можно описать в заявке'], steps: ['Выбрать близкую тему: экология, образование, инклюзия или права детей', 'Проверить актуальный набор на официальной странице', 'Регулярно участвовать и записывать часы и результаты', 'Попросить подтверждение участия и собрать материалы проекта'], important: 'Для портфолио важен не сам сертификат, а конкретный вклад: что ты сделал, для кого и какой получился результат.', portfolio: 'Добавь роль, количество часов, 2–3 выполненные задачи и измеримый результат — например, число участников мероприятия.', url: 'https://www.unicef.org/kazakhstan/волонтерство-0' },
  { name: 'Technovation Girls', age: 'Для участниц 8–18 лет', tag: 'Свой проект', summary: 'Команда создаёт приложение или AI-решение для проблемы своего сообщества.', intro: 'Technovation Girls — бесплатный международный конкурс, где участницы находят проблему вокруг себя, создают технологическое решение, бизнес-план и презентацию проекта.', benefits: ['Готовый проект для портфолио', 'Практика программирования и работы с AI', 'Командная работа и публичная презентация', 'Обратная связь от специалистов'], steps: ['Собрать небольшую команду и выбрать реальную проблему', 'Зарегистрироваться в новый сезон', 'Создать прототип и проверить его на пользователях', 'Подготовить описание влияния, видео и презентацию'], important: 'Регистрация идёт по сезонам и может быть закрыта. Если текущий набор завершён, можно подписаться на уведомление о следующем.', portfolio: 'Покажи ссылку на прототип, свою роль в команде, отзывы пользователей и то, как проект изменился после тестирования.', url: 'https://technovationchallenge.org/get-involved/students/' },
];

export function OpportunityList() {
  const [selected, setSelected] = useState<Opportunity | null>(null);
  useEffect(() => {
    const close = (event: KeyboardEvent) => event.key === 'Escape' && setSelected(null);
    window.addEventListener('keydown', close);
    return () => window.removeEventListener('keydown', close);
  }, []);

  return <><section className="panel"><div className="section-title"><div><p className="eyebrow">Портфолио</p><h2>Возможности усилить заявку</h2></div></div>{opportunities.map(item => <button className="opportunity" key={item.name} onClick={() => setSelected(item)}><div><strong>{item.name}</strong><span>{item.tag}</span></div><p>{item.summary}</p><small>{item.age}</small><b>Подробнее →</b></button>)}</section>
    {selected && <div className="modal-backdrop" onMouseDown={() => setSelected(null)}><article className="program-modal" role="dialog" aria-modal="true" aria-labelledby="program-title" onMouseDown={event => event.stopPropagation()}><button className="modal-close" onClick={() => setSelected(null)} aria-label="Закрыть">×</button><span className="program-tag">{selected.tag}</span><h2 id="program-title">{selected.name}</h2><p className="program-intro">{selected.intro}</p><h3>Чем это поможет</h3><ul>{selected.benefits.map(item => <li key={item}>{item}</li>)}</ul><h3>Что делать по шагам</h3><ol>{selected.steps.map(item => <li key={item}>{item}</li>)}</ol>{selected.portfolio && <div className="portfolio-note"><strong>Что добавить в портфолио</strong><p>{selected.portfolio}</p></div>}<div className="important-note"><strong>Важно</strong><p>{selected.important}</p></div><a className="primary official-button" href={selected.url} target="_blank" rel="noreferrer">Открыть официальный сайт ↗</a><small className="checked-date">Информация проверена 15.07.2026</small></article></div>}
  </>;
}
